from sqlalchemy.orm import Session
from my_agent.models.action_proposal import ActionProposal, ProposalStatus
from app.utils.make_json import normalize_payload

def save_proposals(
    db: Session,
    *,
    thread_id: str,
    user_id: int,
    proposals: list[dict]
) -> list[ActionProposal]:
    """
    Save proposals generated by LangGraph into DB.
    """
    saved = []

    for p in proposals:
        payload = normalize_payload(p["payload"])
        proposal = ActionProposal(
            thread_id=thread_id,
            user_id=user_id,
            action_type=p["action_type"],
            payload=payload ,
            status=ProposalStatus.PENDING
        )

        db.add(proposal)
        saved.append(proposal)

    db.commit()

    for p in saved:
        db.refresh(p)

    return saved
